import Head from 'next/head'
import Image from 'next/image'
import { Slider, PizzaList } from '../components'


export default function Home() {
  return (
    <div>
      <Head>
        <title>A2G Delivery</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Slider />
      <PizzaList />
    </div>
  )
}
