import Head from 'next/head'
import { Slider, PizzaList } from '../components'
import axios from 'axios'
import { useState } from 'react'


export default function Home({pizzaList, admin}) {

  return (
    <div>
      <Head>
        <title>A2G Delivery</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Slider />
      <PizzaList  pizzaList = {pizzaList}/>
    </div>
  )
}
export async function getServerSideProps(ctx) {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }
const res = await axios.get("http://localhost:3000/api/products")

return {
  props: {
    pizzaList: res?.data
  }
}
}